### ISSUE TITLE
Find a “foundation application”

### ISSUE THREAD

**Issue by Hywan** [hoaproject/ActionBoard#13]
We need a “foundation application” to manage the list of subscriptions, cotisations & co.: All the services around a foundation.

Both a heavy application or a web-application are acceptable. Only constraints: Being open-source.
#### Tasks
- [x] Find a “foundation application”.

**Comment by osaris** [comment]
I'll have a look soon but I also ping @CircleCode because he looks to have some references yesterday.

**Comment by Savageman** [comment]
A good start for the research is [this page](http://wiki.april.org/w/Logiciels_de_Gestion_D'Association_%28GDA%29) from the APRIL association (french evangelists).

**Comment by osaris** [comment]
@Savageman +1 I found it yesterday and it looks great.

**Comment by maitrepylos** [comment]
http://galette.eu galette un outil de gestion d'assoc tester avec Atoum, on pourrais peut-être même contribué ? ps: j'ai piqué l'idée chez Grummfy ;)

**Comment by osaris** [comment]
@maitrepylos je ne vois pas beaucoup de tests dans le dépôt :-/ http://git.tuxfamily.org/galette/galette.git/tree/galette (et le code est ... comment dire... bref)

**Comment by maitrepylos** [comment]
Ben c'est marqué dans la page d'accueil du site que le code est bof ;) Bon maintenant si c'est un critère t'es difficile :)

**Comment by osaris** [comment]
@maitrepylos ça donne quand même une info sur la pérennité de l'app, si le bidule ne tourne plus sur PHP7 (par ex) on aura bien l'air malin si on a investi un peu de temps pour configurer etc...

**Comment by Grummfy** [comment]
To choose the right tool, check the functionnalities and what we need and if it work. Don't check the code, overall you will need to dev yourself a new tool.
- galette is well known
- http://fr.grisbi.org/
- many thing can be found on http://framasoft.net/rubrique438.html

**Comment by maitrepylos** [comment]
Note que si tu trouves que le projet remplis tes besoins, je veux bien le tester sur PHP7.

**Comment by Hywan** [comment]
Still 2 days left :-). Tic tac, tic tac :clock11:.

**Comment by osaris** [comment]
Little review of a selection extracted from the [APRIL page](http://wiki.april.org/w/Logiciels_de_Gestion_D'Association_%28GDA%29) :
- Dolibarr : http://www.dolibarr.fr

An ERP with some foundation modules but seems really overkill for me.
- Galette (by tuxfamily - Git : http://git.tuxfamily.org/galette/galette.git/tree/)

Nearly impossible to find a working website so ... 
- GestAssoPhp : http://gestassophp.xtreemhost.com/cms/

Looks horrible (ok not a criteria but...), seriously, no update since 2013, strange licensing (CC but need to ask to download ?!).
- Piwam : http://piwam.com

Written in Ruby (on Rails), looks basic but enough for us. Maintained by the CTO of @eboutic.ch (what a coincidence). 
- Diacamma : http://www.sd-libre.fr

Desktop app, license not found (nor source) ? Can somebody find this ?

Conclusion : all website of these project are crappy, in a big effort I'll test Galette, Piwam, and maybe Diacamma if somebody find license & source ?

**Comment by Hywan** [comment]
Dolibarr looks to be the best one, isn't it :-)?

**Comment by Jir4** [comment]
Seems good to me, after a quick look, i saw that we can enable only the features we need.

**Comment by Hywan** [comment]
Perfect! Typically, we don't want calendar since we have sabre/katana on dav.hoa-project.net, so having them on Dolibarr is totally useless.

**Comment by osaris** [comment]
Well I think it's overkill but If you think it is what we need, I just say "why not" ;-)

**Comment by Hywan** [comment]
@osaris If you think this is overkill, so it's up to you to decide. You are the one who will use this software the most. The final decision belongs to you.

**Comment by maitrepylos** [comment]
@osaris déjà que tu te plains du code de Galette...regarde celui de Dollibar ;)....mais bon si tu as besoin j'ai déjà créé des modules pour ce produit.

**Comment by osaris** [comment]
@Hywan we have a very small volume for the moment so we can go with Dollibar and move away if we discover real problems.

So, next step is to setup Dollibar on our servers ?

**Comment by Hywan** [comment]
Yup. You have access. Go :-]. foundation.hoa-project.net?

**Comment by maitrepylos** [comment]
Hum... 404 Not Found :p

**Comment by Hywan** [comment]
@maitrepylos That's a proposal URL…

**Comment by Hywan** [comment]
We are late here but not for the hardest part. @osaris is installing the application on the server, so it's fine! Keep going!

**Comment by osaris** [comment]
Thanks to @Pierozi the app is now running on http://foundation.hoa-project.net

I'll take some time to configure it so we can leave this issue open until I finished.

**Comment by Hywan** [comment]
@osaris, @Pierozi: :+1:!

**Comment by Hywan** [comment]
@osaris ping?

**Comment by osaris** [comment]
I've started configuring dolibarr but I'm still waiting an answer to my email to @Pierozi about SMTP/sendmail configuration because dolibarr needs to send emails.

**Comment by Pierozi** [comment]
It's stuck by #7 

But like the mail sending are limited to dolibar, I think we can put any SMTP account for do the job.
create a quick mailbox on gandi, gmail, or anywhere and use it.

**Comment by Hywan** [comment]
@osaris Use your GMail account if necessary and if it is temporary.

**Comment by osaris** [comment]
@Hywan done, it works. Configuration is done for me. 

What is the next step ?  We need a join workflow and then we'll send a mail to all prospects to let them know they can join the foundation ?

**Comment by Hywan** [comment]
Next steps are the following:
1. Having the whole infrastructure automated and running,
2. Having mail restored,
3. Having mailing-lists restored,
4. Being able to contact everyone in the foundation to create the bank account (I received the paper but I can't join CircleCode :-(),
5. Create the bank account,
6. Start foundation participations.

It looks like crazy but this is the next steps from my point of view. We can't communicate without mails and need them. We have personal emails at least. Maybe it is enough for what we need to do… but what do we need to do? We have already defined the cotisation amount in the last Hoa Apex meeting. Do you see something else?

**Comment by thehawk970** [comment]
Hywan we talk about 3/4 mail (important) the board of the foundation, you can probably do an alias in gandi dashboard and you can communication with it ;-) people get the alias and don't care about the architecture :p (and in gmail you can send email with this alias).

Cheers

**Comment by Hywan** [comment]
@osaris, @camael24: What kind of email addresses do we need then? Only for the foundation at first?

**Comment by osaris** [comment]
@camael24 @Hywan make sense, that would allow us to move forward with foundation and make a lot of :moneybag:

**Comment by Hywan** [comment]
@osaris What email addresses do we need?

**Comment by osaris** [comment]
@Hywan one for each member of the board and maybe a redirection for foundation@hoa-project.net ?

**Comment by thehawk970** [comment]
@osaris +1 i think to president@, tresorier@, secretaire@ , but just foundation make sense i don't know if you receive lots of mail and so only one adresse make sense to start :)

**Comment by Hywan** [comment]
@osaris foundation@ redirects to what address?

**Comment by Hywan** [comment]
Actually foundation@ redirects to my email.

**Comment by Hywan** [comment]
- :white_check_mark: raphael.emourgeon@hoa is created (cc @osaris),
- :white_check_mark: matthieu.codron@hoa has been created (cc @CircleCode),
- :white_check_mark: ivan.enderlin@hoa was already created.

Next?
