### ISSUE TITLE
Deploy IRC logger

### ISSUE THREAD

**Issue by CircleCode** [hoaproject/ActionBoard#15]
Depends on #2.

IRC logger has to be deployed in our infrastructure.
#### Tasks
- [x] Install logger and connect it to #hoaproject,
- [x] Make logs available through the website.

**Comment by CircleCode** [comment]
@Pierozi is leader on this issue since there is something to install on the servers, but the website part can be achieved by someone else (@pierozi: feel free to reaffect when required)

**Comment by Pierozi** [comment]
@CircleCode Roger :radio:

**Comment by Hywan** [comment]
https://botbot.me/freenode/hoaproject/
