### ISSUE TITLE
Stats on waffle.io

### ISSUE THREAD

**Issue by Grummfy** [hoaproject/ActionBoard#18]
Here is the answer about the stats of waffle : https://github.com/waffleio/waffle.io/issues/2110#issuecomment-145686222

**Comment by Hywan** [comment]
@Grummfy There is one pending question there. Please, can you re-open the issue?

**Comment by Hywan** [comment]
ping?

**Comment by Grummfy** [comment]
> Thanks!
> 
> Here's what we see, for views on any board with the url hoaproject in the last month. This might not be entirely accurate, but it's the best we have right now.
> 
> ![unnamed](https://cloud.githubusercontent.com/assets/668804/10920229/5d2b31e0-826f-11e5-8377-608909cd24b5.png)

this what I got, just now ...

**Comment by Hywan** [comment]
So we must ask anytime we would like some stats? Cool :-p.

**Comment by Hywan** [comment]
Than you for your time @Grummfy!
