### ISSUE TITLE
Update #hoaproject IRC channel topic to mention its logged

### ISSUE THREAD

**Issue by osaris** [hoaproject/ActionBoard#21]
We need to update the #hoaproject IRC channel topic to mention its logged and provide a link to the botbotme page (https://botbot.me/freenode/hoaproject/). The URL can be shortened. This is required by Freenode terms of service.

**Comment by Hywan** [comment]
@osaris https://botbot.me/freenode/hoaproject/2015-11-05/?msg=53486971&page=1

**Comment by Hywan** [comment]
@osaris Thanks for the reminder!
