### ISSUE TITLE
Administrator for the comments

### ISSUE THREAD

**Issue by Hywan** [hoaproject/ActionBoard#5]
Depends on #3.

During Hoa Apex 3rd edition, @camael24 and Cyrano proposed themselves as moderators. I agree with that.

However, Cyrano needs a Github account.
#### Tasks
- [x] @camael24, please, could you ask Cyrano to create a Github account?
- [x] When done, we must include it in the @hoaproject/hoackers team.

**Comment by thehawk970** [comment]
I just send an Twitter direct message to Cyrano

**Comment by thehawk970** [comment]
Le compte de Cyrano est @Cyrano24

**Comment by Jir4** [comment]
So we can call the moderators team, the 24 crew ?

**Comment by Hywan** [comment]
@Cyrano24 has been invited into @hoaproject/hoackers team.

**Comment by jemdev** [comment]
ok, connected now
