### ISSUE TITLE
Machines we need

### ISSUE THREAD

**Issue by Hywan** [hoaproject/ActionBoard#6]
In Hoa Apex 3rd edition, we discussed about our needs regarding machines.

We need 2 machines:
1. Web services, mail and search,
2. CI.

I am writing it here for the history.

**Comment by Savageman** [comment]
(added for reference) CI needs a 2nd machine because it needs **a lot** of VMs (see http://keynote.hoa-project.net/HoaApex14-2/HoaApex14-2.html#25.0)

**Comment by Grummfy** [comment]
well someone speak about having a linux and a windows machine for the ci...

**Comment by Hywan** [comment]
@Grummfy We will start with Linux machines first. We can have Windows inside VM, this is not an issue. Mac OS X will be an issue though.
