### ISSUE TITLE
AWS or Azure?

### ISSUE THREAD

**Issue by Hywan** [hoaproject/ActionBoard#9]
We are going to move our machines in the “cloud” (ouahh). So we have to decide whether we are going for AWS for Azure. Discuss here and explain pros/cos.
#### Tasks
- [x] Why AWS (@Pierozi)
- [x] Why Azure (@Hywan)

**Comment by Grummfy** [comment]
Like I said in apex, I cantact the guy of Azure (the european evangelist of azure). Now they want to contact me by skype. I can explain what we need, but if @Pierozi prefer to speak with him directly is fine too.

**Comment by Hywan** [comment]
@Grummfy Can you invite him here? On the discussion? Our prerequisite are:
- 2 or more machines,
- Free (remind we have a “They support us” section and we promote our sponsors often),
- In Europe but not in France nor UK (preferably in Germany or Switzerland),
- IPv6.

RAM and HDD are modular in the cloud configuration so it's fine.

**Comment by thehawk970** [comment]
The pricing free, imho is not an obstacle.
We must not stop at this detail.

**Comment by Pierozi** [comment]
@Grummfy we need is a full access to our dedicated account for manage ourself the instance, network rules... Expect that up to you to talk with him or invite here in the best.

**Comment by Hywan** [comment]
Pros for Azure so far:
- [2 regions in Europe](https://azure.microsoft.com/en-us/regions/#services) (Ireland and Netherlands),
- Environmental sustainability,
- [CDN](https://azure.microsoft.com/en-us/services/cdn/),
- Actually… a huge number of [services](https://azure.microsoft.com/en-us/regions/#services), most of them available in Europe.

I used the calculator to see get an idea of how it works. For sure, we have small requirements. We don't need a database machine for instance, our website does not need to “scale”, we don't have massive visitors. We also don't need analytics or notifications or scalable API etc.
So, based on the [calculator](https://azure.microsoft.com/en-us/pricing/calculator/), here is what I choosed:
- Virtual Machines.

That's all.
[Price plans](https://azure.microsoft.com/en-us/support/plans/) are the following (for VMs, because it costs 0 by default with the first plan)… so, for VMs, it's:
- Free: Free plan features include:
  - Billing and subscription management,
  - Service dashboard,
  - Web incident submission.
- 24.46EUR/months: Developer plan features include:
  - Web incident submission,
  - Unlimited break/fix 24x7,
  - Fastest response time <8 hours.
- 252.99EUR/month: Standard plan, too much expensive for us.
- 843.30EUR/month: Professional direct plan, too much expensive for us.

There is no extra charge as far as I see.

So we would be interested by the Free plan. Here are more details: https://azure.microsoft.com/en-us/support/plans/. Prices are the same whether we are in North Europe or West Europe.

Consequently, I think we don't need to ask for a free plan, it seems to be free by default. For all our services, virtual machines will do the job quite well. Even the CI needs virtual machines. I wonder, however, how virtual machines we are able to run. I didn't find the information. I am going to dig a little bit more.

**Comment by Hywan** [comment]
Actually this is the Free plan but it's not free. See here for VM pricing details: https://azure.microsoft.com/en-us/pricing/details/virtual-machines/.

**Comment by Hywan** [comment]
Funny article: https://azure.microsoft.com/en-us/campaigns/azure-vs-aws/.

**Comment by Savageman** [comment]
I tried both services once and stayed with AWS because Azure had capped IOPS based on the size of the VM (so small VMs had really bad disk performance).

Since then I use AWS and has some experience with it if you need help.

They also have 2 regions in Europe (Ireland and Frankfurt) and tons of services (database, transactional e-mails, queue, CDN, DNS, ...).

Almost all their services have a [free plan](http://aws.amazon.com/free/) for the first 12 months. The free plan includes a machine with 1 Go RAM ([EC2 tiny instance](http://aws.amazon.com/ec2/instance-types/)) and 30 Go SSD ([EBS storage](http://aws.amazon.com/ebs/details/)).

After the 12-month free period, the 1 Go VM is 10€ per-month, the 2 Go VM is 20€ per-month, SSD storage is 12 cents per Go per month.

**Comment by Hywan** [comment]
Maybe we have to decide now because of #11. @Pierozi: Did you get time to check a little bit AWS? Feedback from @Savageman is interesting.

**Comment by Pierozi** [comment]
Amazon have more than hundred services, so the question about what is possible to do is not really the issue. Now each top cloud provider like Azure or Google had time to catch up Aws.

But i think aws are still the more advanced system, i have servers on Aws and Google, and aws is best, however i don't know about Azure.

The point is we don't need hundred services, maybe one day we may use auto scale, but there too, they have all these features.

And at least, for stay independent we will provide our Server with script, Chef, Puppet, Ansible, Makefile...

So the thing lead our choice are the price. and like Savageman said, Aws offer 750 hours of EC2 instance, 1 year of usage.

There is a link go to AWS Pricing calculator :
 http://calculator.s3.amazonaws.com/index.html#r=FRA&s=EC2&key=calc-4B69F954-67BE-4950-AAB4-C45F1F8A59CA

**Comment by osaris** [comment]
@Pierozi thanks for the feedback, the price is ok for me.

**Comment by Hywan** [comment]
### Conclusion

We go for AWS.

**Comment by Grummfy** [comment]
for information for @Pierozi (because your have moe the habiit of google cloud) : https://medium.com/google-cloud/aws-to-google-cloud-platform-service-mapping-5a1689d41f01
